### ISSUE TITLE
Info screen

### ISSUE THREAD

**Issue by quazzie** [mapero/node-red-contrib-hangouts#1]
You should add some text to the info box for the node.
I have no idea how to use it =)

What is the topic property ?
What is Recipes property ? Is it suppose to be recipients ?
Should recipes be emails or what ?

i tried emails and what i think is a conversationid (UgyxxxxxxvpUjrBzml94AaABAagBq-Dnxx) 
i edited the convid in case there is some sensitive info in there.
But all i get is "bad request".

**Comment by mapero** [comment]
Yeah i will add this information. Its a first version and it is not yet perfect.
recipients is at the moment the gaia_id of your contact. A conversation_id is generated if not exists. You can easily get the id by receiving a message from the contact and look into `msg.event` .
This evening i have some spare time and will write a documentation of the nodes and how to use them. The gaia_id is just for the moment, i'll try to use emails as user ids.

**Comment by mapero** [comment]
Nodes are now using emails for recipients and sender
