### ISSUE TITLE
oauth, wrong user ?

### ISSUE THREAD

**Issue by quazzie** [mapero/node-red-contrib-hangouts#2]
i get the feeling your node gets registered with wrong account.
I have 2 google accounts and when i use the oauth link i select one of them and get a key.
But the in-node reacts only when i get a message on the other user.

And by the way it seems i can't find the app and rewoke the key on any of the users.

**Comment by quazzie** [comment]
Fixed it by using a incognito tab and logged in with that.

**Comment by quazzie** [comment]
Nope, still wrong user...

**Comment by mapero** [comment]
Thats a problem of the underlying library hangupsjs. It saves the cookies as a file in the module folder. They provide a way to define where to save it, but thats not working for me at the moment, so i did not use it. Try to delete the `cookies.json` from that folder. Should be in `node-red-contrib-hangouts/node_modules/hangupjs/`.

At the moment only one account is supported

**Comment by quazzie** [comment]
Ah, ok. 
I used my default account to start and then removed it and used the second account.
I guess the files did not get removed/overwritten.

Thanks!
