### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by beireken** [mapero/node-red-contrib-hangouts#4]
hi,

I'm trying your node, but am getting the following error on injecting a string:
`TypeError: Cannot read property '0' of undefined`

The msg.payload is a string. no other info is passed to the node.

Am i doing something wrong? All info in the hangouts-out node is filled in.

**Comment by mapero** [comment]
Thanks. I will look into it. Did you add the E-Mail address of your contact?

**Comment by beireken** [comment]
Yes, the recipient field has a valid account.

Thx for the quick reply btw!

**Comment by mapero** [comment]
Okay. Need to look into the code this evening. I guess it has something todo with the account lookup.
