### ISSUE TITLE
cannot resolve gaia_id

### ISSUE THREAD

**Issue by beireken** [mapero/node-red-contrib-hangouts#5]
Is it possible the node does not work with some accounts?
I have setup the config node to send from my account A.

As a recipient i set up account B.

I get the following error;

`Error: Cannot resolve gaia_id from contact: xxx@gmail.com`

When i just change the recipient to another account, it works fine.

**Comment by mapero** [comment]
Did you accept the invitation on both sides? I have to check if there is an easier way to lookup the gaia_id. It seems it sometimes fails.

**Comment by beireken** [comment]
Invitation?

I have succesfully sent a message to that account on a different node-red install. BUT only once.
It now returns the same error.

**Comment by mapero** [comment]
In hangout you have to accept a new contact. I'll check later.

**Comment by beireken** [comment]
I never saw an invitation of some sort :)

**Comment by P1Rebo** [comment]
I've experienced the same issue. It somehow ran at a time, but now the error msg comes up, but just with the outgoing node.

**Comment by P1Rebo** [comment]
After playing around modifying the recipients list it seems to work again.

**Comment by mapero** [comment]
I updated the node, can you please check. Now you can enter a gaia_id, email or the fallback_name. If you still have trouble, start node-red with `node-red -v` to enable debug mode. It will print your available contacts in the console window.

You should have chatted with the account at least once.

**Comment by beireken** [comment]
when i use the recipient email i get the following error now:
`TypeError: undefined is not a function`

It works with gaia_id, but my own account does not. Unless i'm using the wrong id. How can i find my correct id?

Also in debug i can see some of my contacts and their emails and id's.
My own account is in there, but not with my own email. That's strange

**Comment by mapero** [comment]
Check https://myaccount.google.com if you have an email address set in your profile.

I don't understand by "but my own account does not". You can not send a message to your self. Hangouts creates a conversation, and you need at least to participants in this conversation.

When exactly does this error pops up? Can you provide your flow so i can reproduce it?

**Comment by beireken** [comment]
I have set an email address in my account settings.

Sorry if i wasn't clear.
I have 2 accounts, one for testing and my personal account.
If i use the testing account, i can send messages to other accounts using their gaia_id except to my own account.
That is why i was wondering how to get my own gaia_id. Because maybe it's just that what's the problem.

If i use my own account to send messages to other accounts it also works.

There's not mucht flow to post. It's just an injector coupled to the hangouts node. When i press the inject button i get that error in the debug pane.
I'm injecting a basic string. But i only get that error when using emails in the recipients.
When i use gaia_id's in the recipients field it seems to work fine.

**Comment by mapero** [comment]
Can you please login in hangouts.google.com with booth accounts and create an conversation. Also please check if there is really no invitation pending, see https://owncloud.jochen-scheib.de/index.php/s/iMcgQS9vd0mgG3y

**Comment by beireken** [comment]
There are no invitations pending on both accounts!
I have created a conversation wiht bot accounts. Still same error.
