### ISSUE TITLE
How to reply to a hangout message

### ISSUE THREAD

**Issue by ScottChapman** [mapero/node-red-contrib-hangouts#6]
So, I've receiving messages, but it looks like the output node needs email address. But the incoming messages have giai_id and client_id

Am I able to use any of those to reply?

It might be useful to have the defaults for the output node be able to wire to the msg from the input node and have it just behave as a reply (with contents in msg.payload or something).

**Comment by mapero** [comment]
God idea. Best would be have msg.conversationid and use this. I will add this

**Comment by ScottChapman** [comment]
I'll watch for the change. Maybe post a simple sample flow to flows.nodered.org that shows a reply to an incoming message?

**Comment by mapero** [comment]
See latest version 0.1.8 and http://flows.nodered.org/flow/7894e70d51856267edfc as minimal example. Please give me a short feedback.

**Comment by ScottChapman** [comment]
I'll give it a shot later tonight. Looks good though!

I assume that in your example it will simply reply with "This is the payload: <whatever it got as input>" ?

**Comment by mapero** [comment]
Yeah. I'll create a more complex example on the weekend.
