### ISSUE TITLE
input node seems flakey

### ISSUE THREAD

**Issue by ScottChapman** [mapero/node-red-contrib-hangouts#7]
Often times I see it disconnect and then try to re-connect. And many times it will just not get messages at all.

Have you seen this at all? I'm wondering if there is just some delay on the google side and I just need to wait for the connection to settle down or something

**Comment by mapero** [comment]
Does it throw a message why it can not connect?

**Comment by mapero** [comment]
Can you please check with the latest version.

**Comment by ScottChapman** [comment]
sure, will probably be this weekend if that's ok

**Comment by mapero** [comment]
Thanks. Keep in mind, that the configuration changed. You now have to provide a conversation id instead of a list of contacts.

**Comment by ScottChapman** [comment]
Yea, I saw that. will have to figure out hot to update my code.
It is too bad that there isn't some easy way to map the gaia id with user's
email addresses. I am keeping my own map, but don't have a solid way of figuring
out given a user's google email address what their corresponding gaia ID is…

On Wed, Feb 24, 2016 at 3:23 PM mapero notifications@github.com wrote:
Thanks. Keep in mind, that the configuration changed. You now have to provide a
conversation id instead of a list of contacts.

**Comment by mapero** [comment]
Closing for now. If you still have problems please reopen.
