### ISSUE TITLE
Receive Ok but problem sending a message

### ISSUE THREAD

**Issue by juancgalvez** [mapero/node-red-contrib-hangouts#9]
When I try to send a message it is not sent and node-red console shows:

22 Feb 13:59:30 - [info] [hangouts-out:84530912.664b6] TypeError: Object [object Object] has no method 'find'

**Comment by juancgalvez** [comment]
This happens in a Windows 7 machine x64 with Node-RED version  v0.10.6 and Node.js  version v0.10.38

**Comment by juancgalvez** [comment]
Installed latest version and now I am getting:

No conversation id provided

**Comment by mapero** [comment]
Did you provide a conversation ID?

**Comment by juancgalvez** [comment]
Yes, I did. Node-red console shows a message saying that the message was sent but is not received at the other end.

How can I get conversation Ids programatically in Node-red?

**Comment by juancgalvez** [comment]
It worked. I installed the latest version buy forgot to refresh Node-red web page to get new configuration.

How can I get conversation Ids programatically in Node-red?

Thank you for your help and Node-red node.

**Comment by mapero** [comment]
Not yet. But the incoming connection contains the ID. If you forward a message from input to output, the payload will be send to this conversation.
